### ISSUE TITLE
FlagSecureHelper - Launcher Activity View Binding Crash - Android 11

### ISSUE THREAD

**Issue by nathaniel-ks** [commonsguy/cwac-security#24]
### CWAC Security Library Use Details
**cwac security version**: `0.8.0`
**cwac security functionality involved**: `FLAG_SECURE`/`FlagSecureHelper` as described [here](https://github.com/commonsguy/cwac-security/blob/master/docs/FLAGSECURE.md#dealing-with-the-issue) with the `getSystemService()` override as specified below.

```
@Override
public Object getSystemService(String name) {
  Object result=super.getSystemService(name);

  return(FlagSecureHelper.getWrappedSystemService(result, name));
}
```

### Bug Description
When using view binding in the launcher `Activity`, the `getSystemService()` code (`FlagSecureHelper.getWrappedSystemService(result, name)`) results in a crash on Android 11/R (api 30) using any combination of views in the layout. However, the crash doesn't happen at that line of code. Instead, the crash is triggered by the line trying to inflate the binding layout (`LayoutBinding.inflate(layoutInflator)`). Commenting out the `getSystemService()` override method fixes the issue. Additionally, it appears to only cause a crash on the initial/launcher `Activity` as another, later launched, `Activity` appears to use view binding without issue. 

### Reproducing
I created a [basic project](https://github.com/commonsguy/cwac-security/files/5875014/view-binding-crash-example-project.zip) to verify the issue. Running the project on an Android 11 device will result in the crash below. Commenting out the `getSystemService()` method in `MainActivity` will fix the issue.

Please let me know if I can provide any other details to help, and thank you for your security work on the Android platform.

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MainActivity}: android.view.InflateException: Binary XML file line #2 in com.example.myapplication:layout/activity_main: Binary XML file line #2 in com.example.myapplication:layout/activity_main: Error inflating class android.widget.LinearLayout
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3449)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: android.view.InflateException: Binary XML file line #2 in com.example.myapplication:layout/activity_main: Binary XML file line #2 in com.example.myapplication:layout/activity_main: Error inflating class android.widget.LinearLayout
     Caused by: android.view.InflateException: Binary XML file line #2 in com.example.myapplication:layout/activity_main: Error inflating class android.widget.LinearLayout
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:852)
        at android.view.LayoutInflater.createView(LayoutInflater.java:774)
        at com.android.internal.policy.PhoneLayoutInflater.onCreateView(PhoneLayoutInflater.java:58)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:928)
        at android.view.LayoutInflater.onCreateView(LayoutInflater.java:948)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1002)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:959)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:657)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:532)
        at com.example.myapplication.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:37)
        at com.example.myapplication.databinding.ActivityMainBinding.inflate(ActivityMainBinding.java:31)
        at com.example.myapplication.MainActivity.onCreate(MainActivity.kt:14)
        at android.app.Activity.performCreate(Activity.java:8000)
        at android.app.Activity.performCreate(Activity.java:7984)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3422)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3601)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
     Caused by: java.lang.UnsupportedOperationException
com.example.myapplication E/AndroidRuntime:     at android.view.WindowManager.getMaximumWindowMetrics(WindowManager.java:481)
        at android.view.ViewConfiguration.<init>(ViewConfiguration.java:423)
        at android.view.ViewConfiguration.get(ViewConfiguration.java:520)
        at android.view.View.<init>(View.java:5317)
        at android.view.View.<init>(View.java:5467)
        at android.view.ViewGroup.<init>(ViewGroup.java:697)
        at android.widget.LinearLayout.<init>(LinearLayout.java:254)
        at android.widget.LinearLayout.<init>(LinearLayout.java:250)
        at android.widget.LinearLayout.<init>(LinearLayout.java:246)
        	... 29 more
```

**Comment by commonsguy** [comment]
I have not been attempting to maintain `FlagSecureHelper`, so I am not surprised that there are problems on newer versions of Android. I will see what I can do, though. Thanks for the detailed report!

**Comment by commonsguy** [comment]
The problem lies in `SecureWindowManagerWrapper`. It was written for the methods that existed back in 2016. Android 11 added two new ones: `getCurrentWindowMetrics()` and `getMaximumWindowMetrics()`. Those need to be added to the wrapper, alongside the other ones that delegate to the wrapped `WindowManager`.

Right now, I am not actively attempting to maintain this library. The `FLAG_SECURE` stuff consists of just three small classes. My recommendation is that you:

- Work off of your own copy of the source (via a fork of the project, copying the classes into your own project, copying the classes into some new module of your project, etc.)
- Add the following methods to your local copy of `SecureWindowManagerWrapper`:

```java
    WindowMetrics getCurrentWindowMetrics() {
        return wm.getCurrentWindowMetrics();
    }

    WindowMetrics getMaximumWindowMetrics() {
        return wm.getMaximumWindowMetrics();
    }
```

That should clear up your problem.

Long term, consider migrating to Jetpack Compose. So far, I have had reasonable luck in getting them to honor `FLAG_SECURE` in child windows:

- https://issuetracker.google.com/issues/143778149
- https://issuetracker.google.com/issues/143778148
